### ISSUE TITLE
Outdated industry access info

### ISSUE THREAD

**Issue by juanfrh** [EPCCed/old-cirrus-website#102]
The following sentence needs to be updated:
_For access to Cirrus and EPCC expertise please contact Thomas Blyth ([t.blyth@epcc.ed.ac.uk](mailto:t.blyth@epcc.ed.ac.uk), +44 131 651 3460) and see the [EPCC Accelerator](https://www.epcc.ed.ac.uk/work-us/industry-engagement-programmes/accelerator) page._

The sentence can be found here:
https://www.cirrus.ac.uk/access/

**Comment by jbeechb** [comment]
Have replaced Thomas with Julien

**Comment by juanfrh** [comment]
Thanks @jbeechb I forgot to mention that the following link is also broken:
https://www.epcc.ed.ac.uk/work-us/industry-engagement-programmes/accelerator
It's in the same sentence: _EPCC Accelerator_

**Comment by jbeechb** [comment]
Removed link

**Comment by jbeechb** [comment]
Removed stale link and added Julien's job title
