### ISSUE TITLE
Description of Cirrus hardware and software is out of date

### ISSUE THREAD

**Issue by aturner-epcc** [EPCCed/old-cirrus-website#36]
The description of the Cirrus hardware at: https://www.cirrus.ac.uk/about/hardware.html does not include the new GPU nodes. 

The software page at: https://www.cirrus.ac.uk/about/software.html is also out of date. It still says that the system uses PBSPro.

**Comment by jbeechb** [comment]
The documentation has been updated with Slurm information rather than PBSPro. 
GPU node information has been added to the hardware page.

**Comment by jbeechb** [comment]
All updated - thanks for pointing out these items.
